### ISSUE TITLE
As a project owner, I want to create (post) a new project in order to help a person or a cause

### ISSUE THREAD

**Issue by ak-philance** [Philance/Philance#10]
_Format Title as shown below_
As a [user identity], I want [desired feature] in order to [goal]

**Acceptance criteria**
Use bullets to describe _what must be true in order for a story to be confirmed that it is working as intended_
* Have a page to create/start/post a new project
* Project sponsor should have to provide project details including:
  * Project name
  * Project description
  * Estimated number of resources (freelancers and volunteers) required
  * Skills needed for the project
  * Impact category of project
  * Location of project
  * Target start date/time of project
  * Target end date/time of project
  * Estimated budget for project (includes payments to be made to freelancers and expenses)
* Notifications should be sent to freelancers and volunteers about this project if it meets their interest criteria

**Secondary Actor**
Project Owner can also be a Project Sponsor.

**System Actors**
Philance Web/App

**Preconditions**
1. User is logged into Philance

**Basic Flow**
1. User navigates projects home page
2. User clicks on create new project
3. User fills out all the required details
4. User clicks on submit

**Alternative Flows**
N/A

**Exception Flows**
_List all the exceptions that could occur while performing the use case_

**Post Conditions**
1. Project is posted on Philance network 
2. Feeds are sent to all users whose skill match the project

**Functional Requirements**
1.	Clicking on create project must open project creation page
2.	All required fields must be clearly distinguishable from optional fields
3.	All fields must have a watermark with data expected in that field
4.	Watermark in the fields must disappear when user inputs data (1 or more characters) into the fields
5.	System must highlight all typos/incorrect spellings/grammatical usage 
6.	System must support Bold, Italic, Color, Underlines, Font, Size, Bullets, undo, redo of connect in project description and project milestones/tasks fields
7.	All values in the multi-selection fields must be displayed in alphabetical order
8.	For all fields that allow multi-selection (Ex:Skills, Impact Category etc.,), list must be sorted with values selected on the top followed by unselected values
9.	Selected values and unselected values must be displayed in alphabetical order
10.	When a user unselects a value, sorting must be as adjusted defined in 6 & 7
11.	User must be able to provide street and/or city and/or state and/or zip and/or country for project location
12.	System must start suggesting address as user inputs data into project location. (This will be helpful to calculate distance wherever required) 
13.	System must show date format in date fields
14.	System must support a calendar for all date fields
15.	System must allow a user to input a project start date that is in the past
16.	System must not allow a user to input a project end data that is in the past
17.	System must allow a project start and end date to on same data
18.	System must allow the user to select currency wherever money is inputted
19.	System must allow user to save a project
20.	 System must allow the user to save a project even when mandatory fields are not filled out 
21.	Saved project must not be visible to public
22.	When a user clicks on Submit/Create Project, system must warn the user if all mandatory details are populated

**UI Use Case Number**
_List all UI Use Case Numbers_

**Backend/API Use Case Number**
_List all Backed/API Use Case Numebers_

**Additional Info**
_Optionally add any context or outside factors to consider here_

**Comment by aksarvepalli** [comment]
@ak-philance Project Sponsor is someone who funds a project. He may not be the actual one creating the need/project. To distinctively identify roles, should we say a project owner as a new actor, who creates the projects?

**Comment by ak-philance** [comment]
Good suggestion Karthik. Project owner sounds fine to me. In some cases, project sponsor and project owner could be same person.

**Comment by aksarvepalli** [comment]
I agree with you Ajay. We should ensure we create roles that support this use case, where a user can be a sponsor and/or owner and/or resource.

**Comment by ak-philance** [comment]
Agreed
