### ISSUE TITLE
Logging out offer no scroll on homepage

### ISSUE THREAD

**Issue by RamSailopal** [Philance/Philance#120]
Takes user to generic home page but doesn't scroll page.

**Comment by RamSailopal** [comment]
https://stackoverflow.com/questions/37738979/reloading-page-in-reactjs - May provide a solution

**Comment by RamSailopal** [comment]
This looks to be only an issue on Windows.

Mac seems to work fine on Firefox
On Windows the issue exists with both Chrome and Firefox.

**Comment by manjotsk** [comment]
This Issue has been Fixed now.
https://github.com/Philance/Philance/commit/7e6e81ecce48c42c5024d081225a2368a082c8fa
