### ISSUE TITLE
As a project owner, I want to view a list of my projects in order to see all the projects that I've posted on Philance

### ISSUE THREAD

**Issue by ak-philance** [Philance/Philance#18]
_Format Title as shown below_
As a [user identity], I want [desired feature] in order to [goal]

**Acceptance criteria**
Use bullets to describe _what must be true in order for a story to be confirmed that it is working as intended_
* Have a page that lists all of my projects
* This page can show the following information:
  * Project ID
  * Project Name
  * Project Status (Active, Closed, Pending)
  * Project Start Date
  * Project %Complete
  * Project %RemainingBudget
* Project sponsor can click on a project from the list to see the project details
* Project sponsor can click on a project from the list to manage that project if it is not closed

**Additional Info**
_Optionally add any context or outside factors to consider here_

**Comment by RamSailopal** [comment]
Jenkins test returns a $STAT

**Comment by RamSailopal** [comment]
Jenkins test returns a PASS

**Comment by RamSailopal** [comment]
Jenkins test returns a PASS

**Comment by RamSailopal** [comment]
Jenkins test returns a PASS

**Comment by RamSailopal** [comment]
Jenkins test returns a PASS

**Comment by RamSailopal** [comment]
Jenkins test returns a PASS
http://18.220.139.218/job/Philance-test/5/
