### ISSUE TITLE
Create ER diagram for MySQL Database Schema for Philance web app

### ISSUE THREAD

**Issue by ak-philance** [Philance/Philance#28]
* Can refer to http://www.vertabelo.com/blog/technical-articles/a-database-model-for-a-freelance-job-platform as a starting point

**Comment by aksarvepalli** [comment]
Attaching an initial version of ER diagram. I will modify it as and when required. I've also uploaded the draw.io source file in the Philance Docs repo.
![philance db er diagram](https://user-images.githubusercontent.com/38540066/40891790-f24fbb8e-6759-11e8-9c07-b42a7bc59606.jpg)

**Comment by ak-philance** [comment]
Cool Karthik! We’ll start using this schema in our front end and API code, and give you our feedback as we go along. Thanks for giving us the framework to work with!

Ajay

Ajay Kapur | CEO
PhiLance
Email: ajay.kapur@philance.org
Cell: 617-797-4289
Linked-In: https://www.linkedin.com/in/ajay-kapur-0231686/
philance.org
