### ISSUE TITLE
Create ProjectMyList API

### ISSUE THREAD

**Issue by ak-philance** [Philance/Philance#44]
API used for:

* Get list of projects created by the logged in user
* Called when user clicks on "My Projects" link in the navigation menu
* Redirects user to 'My Projects' page

See below if using OpenProject
http://docs.openproject.org/apiv3-doc/#header-actions-4

**Comment by VijayKumarGandra** [comment]
Can we get the List of Projects that are created and applied by Logged In user with a differentiation
