### ISSUE TITLE
As a user, I want to get a feed of projects of interest to me in order to get updates on projects of interest

### ISSUE THREAD

**Issue by ak-philance** [Philance/Philance#9]
_Format Title as shown below_
As a [user identity], I want [desired feature] in order to [goal]

**Acceptance criteria**
Use bullets to describe _what must be true in order for a story to be confirmed that it is working as intended_

* Show feed of projects that match interests of logged in user in home page of user after s/he logs in
* User should be able to set filters to customize feed

**Secondary Actor**
_Secondary actors are those who can perform the same use case_

**System Actors**
Philance Server

**Preconditions**
1. User is logged into Philance
2. User has subscribed for feeds on all the projects of his interest

**Basic Flow**
1. User makes updates to a project
2. Philance backend identifies all the users subscribed to this project
3. Philance backend sends a notification to all the users subscribed to this project

**Alternative Flows**
_List all the alternate sequence of steps that an actor can go through to perform the use case_

**Exception Flows**
1. User updated an incorrect email address on his account and as a result, no feed will be sent to the user. Philance system must not update the email address until user authenticates his email address
2. System notifies users who have unsubscribed to a project feed

**Post Conditions**
1. All the users subscribed to a project feed gets notified whenever the project is updated

**Functional Requirements**
1. When a user updates a project, the system must notify all the users subscribed to it
2. System must not send notifications to the users who are on the project team but have not subscribed for the feed

**UI Use Case Number**
_List all UI Use Case Numbers_

**Backend/API Use Case Number**
_List all Backed/API Use Case Numebers_

**Additional Info**
_Optionally add any context or outside factors to consider here_

**Comment by aksarvepalli** [comment]
@ak-philance, as written this use case looks like a system use case rather than a user use case. I'd suggest to re-write it as "As a user, I want to be able to subscribe to project feeds so that I can get notified whenever changes are made on the project"

Please let me know your thoughts.

**Comment by aksarvepalli** [comment]
Thanks Ajay, this helps. But do you think user should have an option to unsubscribe from feeds? And do we send a notification weekly on all the most recent projects or what's new oh Philance?

**Comment by ak-philance** [comment]
I think a feed should always be shown on the home page, since there should be some content displayed there. User should be able to fine tune the content they see by adjusting their interests in the user profile page. Notifications (weekly or some other frequency) can be set in the notification settings (part of user profile page), and if user chooses to get notifications, then system should send those via email. Content of notifications still has to be worked out.
